version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "8080:8080"   # Port giao diện web
      - "50000:50000" # Port để các Agent kết nối
    volumes:
      - ./jenkins_home:/var/jenkins_home     # Lưu trữ dữ liệu Jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Để Jenkins có thể chạy lệnh Docker bên trong container
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh